name: SalesForecasting

on:
  push:
    branches:
      - main

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: sales_forecasting_env
          environment-file: MLProject/conda.yaml
          auto-activate-base: false

      - name: Install MLflow
        run: |
          pip install mlflow dagshub

      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . --env-manager=local

      - name: Get latest run ID
        run: |
          echo "Getting latest run ID..."
          RUN_ID=$(ls -td MLProject/mlruns/0/* | head -1 | xargs basename)
          echo "Latest run ID: $RUN_ID"
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

      - name: Download model artifact
        run: |
          mlflow artifacts download --run-id $RUN_ID --artifact-path model -d ./downloaded
          mv ./downloaded/model ./best_model

      - name: Build Docker Image
        run: |
          mlflow models build-docker --model-uri ./best_model --name sales-forecasting

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and Push Docker Image
        run: |
          docker tag sales-forecasting ${{ secrets.DOCKER_USERNAME }}/sales-forecasting:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/sales-forecasting:latest
