name: SalesForecasting

on:
  push:
    branches:
      - main  # atau ganti dengan nama branch-mu

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: sales_forecasting_env
          environment-file: MLProject/conda.yaml
          auto-activate-base: false

      - name: Install MLflow
        run: |
          pip install mlflow dagshub

      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . --env-manager=local
      - name: Get latest MLflow run_id
        run: |
          echo "Getting latest run ID..."
          python <<EOF
          import mlflow
          client = mlflow.tracking.MlflowClient()
          runs = client.search_runs(experiment_ids=["0"], order_by=["start_time DESC"]) 
          run_id = runs[0].info.run_id
          print(f"Latest run ID: {run_id}")
          with open("${{ github.env }}", "a") as f:
              f.write(f"RUN_ID={run_id}\n")
          EOF

      - name: Download model artifacts from DagsHub
        run: |
          echo "Downloading model artifact for run: $RUN_ID"
          mlflow artifacts download --run-id $RUN_ID --artifact-path model -d ./downloaded
          mv ./downloaded/model ./best_model

      - name: Build Docker Model
        run: |
          mlflow models build-docker --model-uri ./best_model --name sales-forecasting

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker Image
        run: |
          docker tag sales-forecasting ${{ secrets.DOCKER_USERNAME }}/sales-forecasting:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/sales-forecasting:latest
