name: Train Model

on:
  push:
    branches:
      - main  # Ganti sesuai nama branch-mu

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: sales_env
          environment-file: MLProject/conda.yaml
          auto-activate-base: false

      - name: Install dependencies
        run: |
          pip install -r MLProject/requirements.txt
          pip install mlflow

      - name: Run MLflow project
        run: |
          cd MLProject
          mlflow run . --env-manager=local

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/sales-forecasting:latest
