jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: sales_forecasting_env
          environment-file: MLProject/conda.yaml
          auto-activate-base: false

      - name: Install MLflow
        run: |
          pip install mlflow dagshub

      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . --env-manager=local

      - name: Download latest model artifact
        run: |
          cd MLProject
          python download_model.py

      - name: Build Docker Image from MLflow model
        run: |
          mlflow models build-docker --model-uri MLProject/best_model --name sales-forecasting
